# Generated by Django 4.1.3 on 2022-11-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=51)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='Phone',
            new_name='phone',
        ),
    ]
